# Generated by Django 4.2.12 on 2024-06-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=55)),
                ('company_prop_name', models.CharField(max_length=55)),
                ('company_address_line1', models.CharField(max_length=55)),
                ('company_address_line2', models.CharField(max_length=55)),
                ('company_district', models.CharField(max_length=55)),
                ('company_state', models.CharField(max_length=55)),
                ('company_pin', models.CharField(max_length=55)),
                ('company_primary_contact', models.CharField(max_length=55)),
                ('company_secondary_contact', models.CharField(max_length=55)),
                ('company_email', models.CharField(max_length=55)),
                ('company_gstn', models.CharField(max_length=55)),
                ('company_logo', models.CharField(max_length=55)),
                ('company_created_on', models.CharField(max_length=55)),
                ('company_active', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_fname', models.CharField(max_length=45)),
                ('salesman_lname', models.CharField(max_length=45)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.company')),
            ],
        ),
    ]
