# Generated by Django 4.2.12 on 2024-07-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_company_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothecation', models.CharField(max_length=25)),
                ('hypothecationfullname', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Taxation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_regime', models.CharField(max_length=25)),
                ('tax_slab', models.CharField(max_length=45)),
                ('tax_subcategory_a_name', models.CharField(max_length=35)),
                ('tax_subcategory_a_percent', models.IntegerField()),
                ('tax_subcategory_b_name', models.CharField(max_length=35)),
                ('tax_subcategory_b_percent', models.IntegerField()),
                ('tax_start_date', models.DateField()),
                ('tax_end_date', models.DateField()),
                ('tax_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_bank_account_no',
            field=models.CharField(default='NA', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_bank_address',
            field=models.CharField(default='NA', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_bank_ifsc',
            field=models.CharField(default='NA', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_bank_name',
            field=models.CharField(default='NA', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_pan',
            field=models.CharField(default='xxxxxxxxxx', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=75),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_gstn',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_pin',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_primary_contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_secondary_contact',
            field=models.CharField(max_length=10),
        ),
    ]
