# Generated by Django 4.2.12 on 2024-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_hypothecation_taxation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxation',
            name='tax_end_date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxation',
            name='tax_subcategory_a_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='taxation',
            name='tax_subcategory_b_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
