# Generated by Django 4.2.12 on 2024-07-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_taxation_tax_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxation',
            name='tax_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
