# Generated by Django 4.2.12 on 2024-07-01 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_taxation_tax_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxation',
            name='tax_end_date',
            field=models.DateField(default=datetime.date(2099, 7, 1)),
        ),
    ]
