# Generated by Django 4.2.12 on 2024-07-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_taxation_tax_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=55)),
            ],
        ),
    ]
