# Generated by Django 4.2.12 on 2024-07-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=55)),
                ('branch_contact_person', models.CharField(max_length=65)),
                ('branch_contact', models.CharField(max_length=10)),
                ('branch_email', models.EmailField(max_length=65)),
                ('branch_location', models.CharField(max_length=65)),
                ('branch_address_l', models.CharField(max_length=65)),
                ('branch_address_2', models.CharField(max_length=65)),
                ('branch_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.company')),
            ],
        ),
    ]
